### ISSUE TITLE
Unit test assumes that CREDENTIALS_DIR is not set (i.e. fails if set)

### ISSUE THREAD

**Issue by hjacobs** [zalando-stups/tokens#13]
The unit tests fail if the CREDENTIALS_DIR environment variable is set, this should be fixed as unit tests should be context/environment independent:

```
Failed tests: 
14:46:38.583   FileSupplierTest.testNoCredentialsDirSet Expected exception: java.lang.IllegalStateException

**Comment by sarnowski** [comment]
:+1: you can also not just set the environment variable to an empty string like

    CREDENTIALS_DIR="" mvn test

You really have to unset it before:

    unset CREDENTIALS_DIR
    mvn test

**Comment by Annie0431** [comment]
Getting sth like this on executing the code for creating tokens ( the same as given on the main page): 
Exception in thread "main" org.zalando.stups.tokens.AccessTokenUnavailableException: No token available for tokenId 'exampleRO'. Tokens are available for the following tokenIds []
	at org.zalando.stups.tokens.AbstractAccessTokenRefresher.getAccessToken(AbstractAccessTokenRefresher.java:92)
	at org.zalando.stups.tokens.AbstractAccessTokenRefresher.get(AbstractAccessTokenRefresher.java:85)
	at avalonapi.AvalonAPI.generateToken(AvalonAPI.java:146)
	at avalonapi.AvalonAPI.main(AvalonAPI.java:60)
Java Result: 1
